language: csharp
dotnet: 2.1.300
dist: trusty
script:
- dotnet restore maturity-level-one/src/maturity-level-one.sln
- dotnet build maturity-level-one/src/maturity-level-one.sln
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
