language: csharp
dotnet: 2.2.100
dist: xenial
script:
- dotnet --info
- dotnet restore maturity-level-one/src/maturity-level-one.sln
- dotnet build maturity-level-one/src/maturity-level-one.sln
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
