name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - maturity-level-one/*.md
    - maturity-level-two/*.md
    - maturity-level-two/docs/*.md
jobs:
- job: Build_MaturityLevelOne
  displayName: Build & Test Maturity Level One
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      projects: maturity-level-one/src/Codit.LevelOne.sln
      arguments: '--configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: maturity-level-one/tests/Codit.UnitTest/Codit.UnitTest.csproj
      arguments: '--configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'Run integration tests'
    inputs:
      command: test
      projects: maturity-level-one/tests/Codit.IntegrationTest/Codit.IntegrationTest.csproj
      arguments: '--configuration release'
- job: Build_MaturityLevelTwo
  displayName: Build & Test Maturity Level Two
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      projects: maturity-level-two/src/Codit.LevelTwo.sln
      arguments: '--configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: maturity-level-two/tests/Codit.UnitTest/Codit.UnitTest.csproj
      arguments: '--configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'Run integration tests'
    inputs:
      command: test
      projects: maturity-level-two/tests/Codit.IntegrationTest/Codit.IntegrationTest.csproj
      arguments: '--configuration release'
